#   Two Dimensional Numpy
##  Author/Executor: LiR
### Date:22-12-2025

In [1]:
import numpy as np
a = [[1,2,3,4],[21,22,23,24],[31,32,33,34]]
A = np.array(a)
A #.shape(3,3)
#arr[row][col]
#arr[row][col:bis offset]

array([[ 1,  2,  3,  4],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [6]:
# Show the numpy array dimensions
print('dimensions of array: ',A.ndim)

# Show the numpy array shape ROWS x COLUMNS 
print('numpy array shape',A.shape) 

# Show the numpy array size
A.size

dimensions of array:  2
numpy array shape (3, 4)


12

In [69]:
print(A)
# Access the element on the second row and third column
print('\n element A[1, 2] ->',A[1, 2])
# Access the element on the second row and third column
print('A[1][2] ->',A[1][2])
print('rows A[1] ->',A[1])
print('columns A[:][1] ->',A[0:3][1])
# Access the element on the first row and first column
print('A[0][0]->',A[0][0])
# Access the element on the first row and first and second columns
print('\nA[0][0:2]->',A[0][0:2])
# Access the element on the first and second rows and third column
print('\nA[0:2, 2 ->',A[0:2, 2])

print(A[:, 1])       # Accessing a column (2nd column)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 element A[1, 2] -> 7
A[1][2] -> 7
rows A[1] -> [5 6 7 8]
columns A[:][1] -> [5 6 7 8]
A[0][0]-> 1

A[0][0:2]-> [1 2]

A[0:2, 2 -> [3 7]
[ 2  6 10]


In [44]:
# Create a numpy array X
X = np.array([[1, 0], [0, 1]]) 
# Create a numpy array Y
Y = np.array([[2, 1], [1, 2]]) 
print(X,'\n-------\n',Y)
# Add X and Y
Z = X + Y
print('\nZ = X + Y->\n',Z)

[[1 0]
 [0 1]] 
-------
 [[2 1]
 [1 2]]

Z = X + Y->
 [[3 1]
 [1 3]]


In [47]:
# Create a numpy array Y
Y = np.array([[2, 1], [1, 2]]) 
print(Y)
# Multiply Y with 2
Z = 2 * Y
print('\n2 * Y\n',Z)

[[2 1]
 [1 2]]

2 * Y
 [[4 2]
 [2 4]]


In [51]:
# Create a numpy array Y
Y = np.array([[2, 1], [1, 2]]) 
print(Y)
# Create a numpy array X
X = np.array([[1, 0], [0, 1]]) 
print(X)
# Multiply X with Y
Z = X * Y
print('Z = X * Y->\n',Z)

[[2 1]
 [1 2]]
[[1 0]
 [0 1]]
Z = X * Y->
 [[2 0]
 [0 2]]


In [ ]:
# Create a matrix A
A = np.array([[0, 1, 1], [1, 0, 1]])
print(A)
# Create a matrix B
B = np.array([[1, 1], [1, 1], [-1, 1]])
print(B)
# Calculate the dot product (умножает и суммирует)
Z = np.dot(A,B)
print('Z = np.dot(A,B)\n',Z)
# Calculate the sine of Z
print('\n np.sin(Z)\n',np.sin(Z))

[[0 1 1]
 [1 0 1]]
[[ 1  1]
 [ 1  1]
 [-1  1]]
Z = np.dot(A,B)
 [[0 2]
 [0 2]]

 np.sin(Z)
 [[0.         0.90929743]
 [0.         0.90929743]]


In [75]:
# Create a matrix A
A = np.array([-1, 1])
#print(A)
# Create a matrix B
B = np.array([1, 1])
#print(B)
# Calculate the dot product (умножает и суммирует)
Z = np.dot(A,B)
Z

0

In [90]:
X=np.array([[1,0,1],[2,2,2]]) 
print(X)
out=X[0:2,2]
out.T

[[1 0 1]
 [2 2 2]]


array([1, 2])

In [60]:
# Create a matrix C
C = np.array([[1,1],[2,2],[3,3]])
print(C)
# Get the transposed of C columns -> rows
print('\n',C.T)

[[1 1]
 [2 2]
 [3 3]]

 [[1 2 3]
 [1 2 3]]


In [62]:
#Consider the following list a, convert it to Numpy Array.
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
A = np.array(a)
A


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
#Calculate the numpy array size.
A.size

12

In [64]:
#Access the element on the first row and first and second columns.
A[0][0:2]

array([1, 2])

In [68]:
#Perform matrix multiplication with the numpy arrays A and B.
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
Z = np.dot(A,B)
Z

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])